routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::get('/user/logout', [App\Http\Controllers\UserController::class, 'logout'])->name('user.logout');
Route::get('/swtich-lang/{lang}', [App\Http\Controllers\LanguageController::class, 'switchLang'])->name('language.change');

Route::get('/greeting/create-en', [App\Http\Controllers\LanguageController::class, 'createGreeting'])->name('language.greeting_create_en');
Route::post('/greeting/save/en', [App\Http\Controllers\LanguageController::class, 'greetingEn'])->name('language.greeting_en');
Route::get('/greeting/kh', [App\Http\Controllers\LanguageController::class, 'greetingKh'])->name('language.greeting_kh');
Route::post('/greeting/kh/save', [App\Http\Controllers\LanguageController::class, 'greetingkhSave'])->name('language.greeting_kh_save');

Route::group(['middleware' => ['auth', 'useraction']], function(){
    Route::get('/', function () {
        return view('welcome');
    });

    // dashbaord 
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('get-chart-data', [App\Http\Controllers\HomeController::class, 'getChartData'])->name('home.get_cart_data');


    // employee 
    Route::get('employee', [App\Http\Controllers\EmployeeController::class, 'index'])->name('employee.index');
    Route::get('employee/create', [App\Http\Controllers\EmployeeController::class, 'create'])->name('employee.create');
    Route::post('employee/save', [App\Http\Controllers\EmployeeController::class, 'save'])->name('employee.save');
    Route::get('employee/edit/{id}', [App\Http\Controllers\EmployeeController::class, 'edit'])->name('employee.edit');
    Route::post('employee/update', [App\Http\Controllers\EmployeeController::class, 'update'])->name('employee.update');

    // employee work experience
    Route::get('employee/experience', [App\Http\Controllers\EmployeeController::class, 'workExperience'])->name('employee.work_experience');
    // employee family info
    Route::get('employee/family-info', [App\Http\Controllers\EmployeeController::class, 'familyInfo'])->name('employee.family_info');

    
    // users
    Route::get('/user/list', [App\Http\Controllers\UserController::class, 'index'])->name('user.list');
    Route::post('/user/save', [App\Http\Controllers\UserController::class, 'save'])->name('user.save');
    Route::post('/user/update', [App\Http\Controllers\UserController::class, 'update'])->name('user.update');
    
    Route::get('/village/list', [App\Http\Controllers\VillageController::class, 'index'])->name('village.index');
    Route::post('/village/save', [App\Http\Controllers\VillageController::class, 'save'])->name('village.save');
    Route::get('/village/edit/{id}', [App\Http\Controllers\VillageController::class, 'edit'])->name('village.edit');
    Route::post('/village/update', [App\Http\Controllers\VillageController::class, 'update'])->name('village.update');
    Route::get('/village/delete/{id}', [App\Http\Controllers\VillageController::class, 'delete'])->name('village.delete');
   
    // commune 
    Route::get('/commune/list', [App\Http\Controllers\CommuneController::class, 'index'])->name('commune.index');
    Route::get('/commune/edit/{id}', [App\Http\Controllers\CommuneController::class, 'edit'])->name('commune.edit');

    // district
    Route::get('/district/list', [App\Http\Controllers\DistrictController::class, 'index'])->name('district.index');
    Route::get('/district/edit/{id}', [App\Http\Controllers\DistrictController::class, 'edit'])->name('district.edit');

    // province
    Route::get('/province/list', [App\Http\Controllers\ProvinceController::class, 'index'])->name('province.index');
    
    //Role
    Route::get('/role/list', [App\Http\Controllers\RoleController::class, 'index'])->name('role.index');
    // permission 
    Route::get('/permission/list', [App\Http\Controllers\PermissionController::class, 'index'])->name('permission.index');
    // permission feature
    Route::get('/permission-feature/list/{id}', [App\Http\Controllers\PermissionFeatureController::class, 'index'])->name('permission_feature.index');
    // role permision
    Route::get('/role-permission/list/{roel_id}', [App\Http\Controllers\RolePermissionController::class, 'index'])->name('role_permission.index');
    Route::get('/role-permission/regenerate', [App\Http\Controllers\RolePermissionController::class, 'reGenerateRole'])->name('role_permission.regenerate');
    // save role permission 
    Route::post('/role-psermission/save', [App\Http\Controllers\RolePermissionController::class, 'savePermission'])->name('role_permission.save');


    Route::get('/district-by-id', [App\Http\Controllers\DistrictController::class, 'getDistrictById'])->name('district.get_by_province_id');
    Route::get('/commune-by-id', [App\Http\Controllers\CommuneController::class, 'getCommuneById'])->name('commune.get_by_district_id');
    Route::get('/village-by-id', [App\Http\Controllers\VillageController::class, 'getVillageById'])->name('village.get_by_commune_id');


    // base actoins 
    Route::post('/base-action/save', [App\Http\Controllers\BaseController::class, 'save'])->name('base_action.save');
    Route::get('/base-action/edit', [App\Http\Controllers\BaseController::class, 'edit'])->name('base_action.edit');
    Route::post('/base-action/update', [App\Http\Controllers\BaseController::class, 'update'])->name('base_action.update');
    Route::get('/base-action/delete', [App\Http\Controllers\BaseController::class, 'delete'])->name('base_action.delete');

    Route::group(['prefix'=>'report','as'=>'report.'], function(){
        Route::get('/list-employee', [App\Http\Controllers\ReportController::class, 'listEmployee'])->name('list_employee');
    });
});

Route::get('/no-permission', function(){
    echo "You don't have permissoin!";
})->name('no-permission');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @yield('tab-title')
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('assets/plugins/fontawesome-free/css/all.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <!-- <link rel="stylesheet"
        href="{{asset('assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')}}"> -->
    <!-- iCheck -->
    <!-- <link rel="stylesheet" href="{{asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css')}}"> -->
    <!-- JQVMap -->
    <!-- <link rel="stylesheet" href="{{asset('assets/plugins/jqvmap/jqvmap.min.css')}}"> -->
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css')}}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
    <!-- Daterange picker -->
    <!-- <link rel="stylesheet" href="{{asset('assets/plugins/daterangepicker/daterangepicker.css')}}"> -->
    <!-- summernote -->
    <!-- <link rel="stylesheet" href="{{asset('assets/plugins/summernote/summernote-bs4.min.css')}}"> -->
     <!-- SweetAlert2 -->
    <link rel="stylesheet" href="{{asset('assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css')}}">
    <!-- Toastr -->
    <link rel="stylesheet" href="{{asset('assets/plugins/toastr/toastr.min.css')}}">
      <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('assets/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    @yield('css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="{{asset('assets/dist/img/AdminLTELogo.png')}}" alt="AdminLTELogo"
                height="60" width="60">
        </div>

        <!-- navbar  -->
        @include('layouts.navbar')
        <!-- sidebar  -->
        @include('layouts.sidebar')

        <!-- dynamic content  -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0">Dashboard</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active">Dashboard v1</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div> -->
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- @if(session()->get('error'))
                    <div class="mt-3 alert alert-danger alert-dismissible fade show" role="alert">
                        {{session()->get('error')}}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        </div>
                    @endif
                    @if(session()->has('success'))
                    <div class="mt-3 alert alert-success alert-dismissible fade show" role="alert">
                    {{session()->get('success')}}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif -->

                    @yield('content')
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.content -->
        </div>


        <!-- jQuery -->
        <script src="{{asset('assets/plugins/jquery/jquery.min.js')}}"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="{{asset('assets/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
        $.widget.bridge('uibutton', $.ui.button)
        </script>
        <!-- Bootstrap 4 -->
        <script src="{{asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
      
        <!-- overlayScrollbars -->
        <script src="{{asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>

        <!-- SweetAlert2 -->
        <script src="{{asset('assets/plugins/sweetalert2/sweetalert2.min.js')}}"></script>
        
        <!-- Toastr -->
        <script src="{{asset('assets/plugins/toastr/toastr.min.js')}}"></script>

        <!-- Select2 -->
        <script src="{{asset('assets/plugins/select2/js/select2.full.min.js')}}"></script>

        <!-- AdminLTE App -->
        <script src="{{asset('assets/dist/js/adminlte.js')}}"></script>
   
       <script>
            //Initialize Select2 Elements
            $('.select2').select2()

            //Initialize Select2 Elements
            $('.select2bs4').select2({
            theme: 'bootstrap4'
            })
       </script>

       @if(session()->has('success'))
       <script>
         var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 5000
            });
            Toast.fire({
                icon: 'success',
                title: "{{session()->get('success')}}"
            })
       </script>
       @endif
       @if(session()->has('error'))
       <script>
         var Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000
            });
            Toast.fire({
                icon: 'error',
                title: "{{session()->get('error')}}"
            })
       </script>
       @endif
        @yield('js')
</body>

</html>

resources/views/layouts/navbar.blade.php
<style>
  /* .main-header *{
    color: white;
  } */
</style>
<nav class="main-header navbar navbar-expand navbar-primary navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav text-white">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <!-- <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link text-white">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link text-white">Contact</a>
      </li> -->
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-user"></i>
          <!-- <span class="badge badge-warning navbar-badge">15</span> -->
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- <span class="dropdown-item dropdown-header">15 Notifications</span> -->
          <div class="dropdown-divider"></div>
          
            <?php 
              if(session()->has('locale')){
                if(session()->get('locale') == 'en'){
                  $lang_label = "Change to Khmer";
                  $lang = 'kh';
                }else{
                  $lang_label = "Change to English";
                  $lang = 'en';
                }
              }else{
                $lang_label = "Change to Khmer";
                $lang = 'kh';
              }
            ?>
            <a href="{{route('language.change', $lang)}}" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> {{$lang_label}}
            <!-- <span class="float-right text-muted text-sm"></span> -->
          </a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-controlsidebar-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li> -->
    </ul>
  </nav>

resources/views/layouts/sidebar.blade.php
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{{asset('assets/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('assets/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <!-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
         
          <li class="nav-item">
            <a href="{{route('home')}}" class="nav-link" id="menu_dashboard">
              <i class="nav-icon fas fa-th"></i>
              <p>
                {{__('t.Dashboard')}}
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{route('employee.index')}}" class="nav-link" id="menu_employee">
              <i class="nav-icon fas fa-users"></i>
              <p>
                {{__('t.Employee')}}
              </p>
            </a>
          </li>
          <li class="nav-item" id="menu_report">
            <a href="#" class="nav-link" >
              <i class="nav-icon fas fa-cogs"></i>
              <p>
                Reports
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('report.list_employee')}}?per_page=5" class="nav-link" id="menu_report_list_meployee">
                  <i class="far fa-circle nav-icon"></i>
                  <p>List Employee</p>
                </a>
              </li>
            </ul>
          </li>

           <li class="nav-item" id="menu_setting">
            <a href="#" class="nav-link" >
              <i class="nav-icon fas fa-cogs"></i>
              <p>
                Settings
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{{route('language.greeting_create_en')}}" class="nav-link" id="menu_greeting_en">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Greeting En</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('language.greeting_kh')}}" class="nav-link" id="menu_greeting_en">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Greeting Kh</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('user.list')}}" class="nav-link" id="menu_user">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Users</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('role.index')}}" class="nav-link" id="menu_role">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Role</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('permission.index')}}" class="nav-link" id="menu_permission">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Permission (Dev Only)</p>
                </a>
              </li>
              @if(check_permission('province', 'view'))
              <li class="nav-item">
                <a href="{{route('province.index')}}" class="nav-link" id="menu_province">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Provinces</p>
                </a>
              </li>
              @endif
              <li class="nav-item">
                <a href="{{route('district.index')}}" class="nav-link" id="menu_district">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Districts</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('commune.index')}}" class="nav-link" id="menu_commune">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Communes</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{route('village.index')}}" class="nav-link" id="menu_village">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Villages</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="{{route('user.logout')}}"> <i class="fa fa-signin-alt"></i> Logout {{auth()->user()->role_id}}</a>
          </li>
  
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>